 site_name: Личный кабинет AP Logistics
 site_description: Инструкция для Клиента
 site_author: Ipiton (Elvira Vaiman)

 theme:
  language: ru # русифицирует сайт, https://ultrabug.github.io/mkdocs-static-i18n/, https://github.com/ultrabug/mkdocs-static-i18n

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black # Цвет заголовка
      accent: indigo # Цвет при наведении на ссылку
      toggle:
        icon: material/lightbulb
        name: Включить темную тему

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo # Цвет при наведении на ссылку
      toggle:
        icon: material/lightbulb-outline
        name: Включить светлую тему
  admonition:
    <type>: <material/alert-circle>

  name: material # тема оформления сайта https://squidfunk.github.io/mkdocs-material/
  logo: bigcartel.png
  favicon: bigcartel.png

  features:
      - navigation.tabs # перемещает навигационное меню наверх
      - navigation.top
      - toc.integrate
      - navigation.expand
      - content.tabs.link # прячет заголовок
      - navigation.sections # убирает раскрывающуюся навигацию
      - navigation.expand # всегда раскрытая навигация
      - navigation.tracking
      - navigation.indexes
      - toc.follow
      - content.code.copy
      - header.autohide
      - search.suggest
      - search.highlight
      
 markdown_extensions:
    - admonition # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#admonition
    - pymdownx.details
    - md_in_html
    - pymdownx.blocks.caption
    - def_list
    - pymdownx.betterem
    - pymdownx.blocks.caption
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde    
    - pymdownx.critic
    - abbr
    - attr_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.emoji:
       emoji_index: !!python/name:material.extensions.emoji.twemoji
       emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.snippets
    - tables
    - footnotes
    - toc:
        permalink: ⚓︎ #убирает якоря на заголовках
        permalink_title: К разделу
        title: На этой странице
 
 
 plugins:
    - search:
        lang:
          - ru

    - glightbox: # https://github.com/blueswen/mkdocs-glightbox#usage
        touchNavigation: true
        loop: false
        effect: zoom
        slide_effect: slide
        width: 100%
        height: auto
        zoomable: true
        draggable: true
        skip_classes:
          - custom-skip-class-name
        auto_themed: false
        auto_caption: false
        caption_position: bottom
        background: white
        shadow: true
        manual: false
        
 extra:
     generator: false
     analytics:
         provider: google
         property: G-FYVP33C6EY
         feedback:
            title: Справка была полезной?
            ratings:
              - icon: material/emoticon-happy-outline
                name: Да, информативно
                data: 1
                note: >-
                  Благодарим за обратную связь!
              - icon: material/emoticon-sad-outline
                name: Нет, не информативно
                data: 0
                note: >-
                  Благодарим за обратную связь!
     social:
        - icon: fontawesome/brands/slack
          link: https://ap-logistics.ru
          name: Ipiton Company
          
 copyright: Copyright &copy; 2025 Ipiton Company
                  
 extra_css:
    - stylesheets/extra.css
    
 nav:
    - Приветствуем!: index.md
    - Начало работы:
        - Основные шаги: start.md
        - Работа с заявками: warehouse-request.md
        - Номенклатура:
            - Формирование номенклатуры: formation-nomenclature.md
        - Запросы менеджеру: requests-manager.md
    - О сервисе: about-service.md
    